package com.example.mm.utils.database;

public enum DatabaseQueriesNames {
    GET_USERID_FROM_USERNAME,
    GET_ALL_PRODUCTS,
    GET_ALL_PRODUCTS_BY_PRICE_ASC,
    GET_ALL_PRODUCTS_BY_PRICE_DESC,
    GET_PRODUCTS_BY_NAME,
    GET_PRODUCTS_FOR_USER,
    GET_LAST_CART_ID_FOR_USER,
    GET_ALL_USERS,
    BUILD_NEW_CART_FOR_USER,
    ADD_PRODUCT_TO_NEW_CART,
    ADD_PRODUCT_TO_EXISTING_CART,
    GET_USER_ID_AND_PASSWORD_FROM_USERNAME,
    BUILD_USER_FROM_USERNAME_AND_PASSWORD,
    BUILD_USER_INVOICE
}

